### ISSUE TITLE
input () got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by AndreiClouds** [polymaster3313/Polyaccess#4]
config.py found
backdoor.py found
keylogger.py found
getinfo.py found
weakcheck.py found
elevated.py found
requirements. txt found
LHOST: 172.3.92.21
LPORT: 5555
yeah something went wrong 101
input () got an unexpected keyword argument 'encoding'

**Comment by eggkingo** [comment]
are you really using python3? or are you using python 2??

*PolyAccess only supports python 3.10 and above (README.md)*

run "python --version" on your cmd and check the output

**Comment by polymaster3313** [comment]
no reply , closed the issue
